第 2 段：词袋模型（Bag of Words）

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
"""计算机不认识文字，只认识数字。
CountVectorizer 的作用就是：统计出所有文档中出现了哪些不同的词（去重） → 这些词就是“特征”（列名）。
数一数每个文档里，这些词分别出现了多少次 → 构成每一行的数字。"""
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
#vectorizer.fit_transform(corpus) = “先扫描所有文本，建立一份完整的词汇表；再拿着这份词汇表，把每句话转化成统计词频的数字表格。”
print("特征名称:", vectorizer.get_feature_names_out())
print("词频矩阵:\n", X.toarray())

特征名称: ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
词频矩阵:
 [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


第 3 段：TF-IDF

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
"""在一个文档中反复出现，但在其他文档中很少出现的词，得分最高（最重要）；到处都出现的词（如 "the"、"is"），得分会被压低。"""
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(corpus)

print("特征名称:", tfidf_vectorizer.get_feature_names_out())
print("TF-IDF矩阵:\n", X_tfidf.toarray())

特征名称: ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
TF-IDF矩阵:
 [[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


第 4 段：N-gram 模型

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

# Bigram（2-gram）,只提取连续的两个词，称为Bigram或2-gram。
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2))
X_bigram = bigram_vectorizer.fit_transform(corpus)

print("Bigram特征:", bigram_vectorizer.get_feature_names_out())

# 若要同时使用 Unigram + Bigram，可设置 ngram_range=(1, 2)
unigram_bigram_vectorizer = CountVectorizer(ngram_range=(1, 2))
X_unigram_bigram = unigram_bigram_vectorizer.fit_transform(corpus)
print("\nUnigram+Bigram特征:", unigram_bigram_vectorizer.get_feature_names_out())

Bigram特征: ['and this' 'document is' 'first document' 'is the' 'is this'
 'second document' 'the first' 'the second' 'the third' 'third one'
 'this document' 'this is' 'this the']

Unigram+Bigram特征: ['and' 'and this' 'document' 'document is' 'first' 'first document' 'is'
 'is the' 'is this' 'one' 'second' 'second document' 'the' 'the first'
 'the second' 'the third' 'third' 'third one' 'this' 'this document'
 'this is' 'this the']


第 5 段：Word2Vec（Gensim）

In [6]:
from gensim.models import Word2Vec

# 准备语料（分词后的句子列表）
sentences = [
    ["cat", "say", "meow"],
    ["dog", "say", "woof"]
]

# 训练 Word2Vec 模型
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)

# 获取词向量
vector = model.wv['cat']
print("'cat' 的词向量（前10维）:", vector[:10])

# 查找相似词
similar_words = model.wv.most_similar('cat')
print("与 'cat' 最相似的词:", similar_words)

'cat' 的词向量（前10维）: [-0.00713902  0.00124103 -0.00717672 -0.00224462  0.0037193   0.00583312
  0.00119818  0.00210273 -0.00411039  0.00722533]
与 'cat' 最相似的词: [('dog', 0.17018885910511017), ('woof', 0.004503022879362106), ('say', -0.027750348672270775), ('meow', -0.04461711645126343)]


第 6 段：FastText（Gensim）

In [7]:
from gensim.models import FastText
"""FastText先根据训练语料建立词汇表，再把每个词拆成若干字符片段，通过上下文训练完整词和字符片段的向量，最后组合成这个词的词向量。"""
# 准备语料
sentences = [
    ["cat", "say", "meow"],
    ["dog", "say", "woof"]
]

# 训练 FastText 模型
model = FastText(sentences, vector_size=100, window=5, min_count=1, workers=4)

# 即使单词不在词典中也能获得向量
vector = model.wv['unseenword']
print("未登录词 'unseenword' 的词向量（前10维）:", vector[:10])

未登录词 'unseenword' 的词向量（前10维）: [ 5.4909813e-04 -1.6984715e-03  5.3171698e-05  5.7649589e-04
 -1.8298440e-03 -8.8382221e-04 -1.2560639e-03 -2.2395812e-04
  5.3206331e-04 -6.9465803e-04]


补充：GloVe 词向量

In [6]:
import gensim.downloader as api
"""根据整个语料库中词语共同出现的次数和规律，为每个词学习一个稠密向量。它会统计整个语料库中的词语共现关系，而不仅仅观察某一个局部训练样本.GloVe先建立词表，再统计词表中不同词语在上下文窗口内共同出现的次数，最后根据共现关系训练每个词的向量。"""

# ============================================================
# 1. 下载并加载预训练GloVe词向量
# ============================================================

print("正在加载预训练GloVe词向量……")
print("第一次运行需要下载，后续会读取本地缓存。")

glove_model = api.load(
    "glove-wiki-gigaword-50"
)

print("GloVe词向量加载成功！")


# ============================================================
# 2. 查看模型的基本信息
# ============================================================

print("\n词向量维度：")
print(glove_model.vector_size)

print("\n词表中的词语数量：")
print(len(glove_model.index_to_key))

print("\n词表前10个词：")
print(glove_model.index_to_key[:10])


# ============================================================
# 3. 获取cat的GloVe词向量
# ============================================================

word = "cat"

if word in glove_model.key_to_index:
    vector = glove_model[word]

    print(f"\n'{word}' 的完整向量维度：")
    print(vector.shape)

    print(f"\n'{word}' 的GloVe词向量前10维：")
    print(vector[:10])
else:
    print(f"\n词表中不存在单词：{word}")


# ============================================================
# 4. 计算两个词的相似度
# ============================================================

word1 = "cat"
word2 = "dog"

if (
    word1 in glove_model.key_to_index
    and word2 in glove_model.key_to_index
):
    similarity = glove_model.similarity(
        word1,
        word2
    )

    print(
        f"\n'{word1}' 与 '{word2}' 的相似度："
    )
    print(similarity)


# ============================================================
# 5. 查询与cat最相似的词
# ============================================================

print(f"\n与'{word}'最相似的10个词：")

similar_words = glove_model.most_similar(
    positive=[word],
    topn=10
)

for similar_word, score in similar_words:
    print(
        f"{similar_word:<15}"
        f"相似度：{score:.4f}"
    )

正在加载预训练GloVe词向量……
第一次运行需要下载，后续会读取本地缓存。


C:\Users\Administrator\.conda\envs\rl\lib\ssl.py:570: UserWarning: unable to load Windows certificates, some may be corrupted
  warnings.warn("unable to load Windows certificates, some may be corrupted")


[==================================================] 100.0% 66.0/66.0MB downloaded
GloVe词向量加载成功！

词向量维度：
50

词表中的词语数量：
400000

词表前10个词：
['the', ',', '.', 'of', 'to', 'and', 'in', 'a', '"', "'s"]

'cat' 的完整向量维度：
(50,)

'cat' 的GloVe词向量前10维：
[ 0.45281  -0.50108  -0.53714  -0.015697  0.22191   0.54602  -0.67301
 -0.6891    0.63493  -0.19726 ]

'cat' 与 'dog' 的相似度：
0.9218005

与'cat'最相似的10个词：
dog            相似度：0.9218
rabbit         相似度：0.8488
monkey         相似度：0.8041
rat            相似度：0.7892
cats           相似度：0.7865
snake          相似度：0.7799
dogs           相似度：0.7796
pet            相似度：0.7792
mouse          相似度：0.7732
bite           相似度：0.7729


第 7 段：BERT 词向量（HuggingFace Transformers）

In [1]:
from pathlib import Path

import torch
from transformers import AutoModel, AutoTokenizer


# ============================================================
# 1. 指定本地英文BERT模型文件夹
# ============================================================

model_dir = Path(
    r"D:\11\NLP\data\hf_cache_bert_uncased"
)


# ============================================================
# 2. 检查模型文件夹是否存在
# ============================================================

if not model_dir.is_dir():
    raise FileNotFoundError(
        f"模型文件夹不存在：{model_dir}\n"
        "请先创建该文件夹，并放入下载好的模型文件。"
    )


# ============================================================
# 3. 检查必要文件
# ============================================================

required_files = [
    "config.json",
    "tokenizer_config.json",
    "tokenizer.json",
    "vocab.txt",
    "model.safetensors"
]

missing_files = []

for file_name in required_files:
    file_path = model_dir / file_name

    if not file_path.is_file():
        missing_files.append(file_name)


if missing_files:
    raise FileNotFoundError(
        "本地模型文件不完整，缺少：\n"
        + "\n".join(missing_files)
        + f"\n\n请把文件放到：{model_dir}"
    )


print("本地模型文件检查成功！")

for file_name in required_files:
    file_path = model_dir / file_name

    print(
        f"{file_name:<25}"
        f"{file_path.stat().st_size / 1024 / 1024:.2f} MB"
    )


# ============================================================
# 4. 完全从本地加载分词器
# ============================================================

tokenizer = AutoTokenizer.from_pretrained(
    str(model_dir),

    # 只读取本地文件，绝不联网
    local_files_only=True,

    # 使用tokenizer.json快速分词器
    use_fast=True
)

print("\n英文BERT分词器加载成功！")


# ============================================================
# 5. 完全从本地加载BERT模型
# ============================================================

model = AutoModel.from_pretrained(
    str(model_dir),

    # 只读取本地文件，绝不联网
    local_files_only=True
)

print("英文BERT模型加载成功！")


# ============================================================
# 6. 切换到推理模式
# ============================================================

model.eval()


# ============================================================
# 7. 准备输入文本
# ============================================================

text = "Helloj, my dog is cute"


# ============================================================
# 8. 文本编码
# ============================================================

inputs = tokenizer(
    text,
    return_tensors="pt"
)


# ============================================================
# 9. 查看实际Token
# ============================================================

tokens = tokenizer.convert_ids_to_tokens(
    inputs["input_ids"][0]
)

print("\n原始文本：")
print(text)

print("\n分词结果：")
print(tokens)

print("\ninput_ids：")
print(inputs["input_ids"])

print("\nattention_mask：")
print(inputs["attention_mask"])

if "token_type_ids" in inputs:
    print("\ntoken_type_ids：")
    print(inputs["token_type_ids"])


# ============================================================
# 10. 前向传播
# ============================================================

with torch.no_grad():
    outputs = model(**inputs)


# ============================================================
# 11. 取得最后一层隐藏状态
# ============================================================

last_hidden_states = outputs.last_hidden_state


# ============================================================
# 12. 输出结果
# ============================================================

print("\n输入Token数量：")
print(inputs["input_ids"].shape[1])

print("\n最后一层隐藏状态形状：")
print(last_hidden_states.shape)


# ============================================================
# 13. 查看每个Token对应向量的形状
# ============================================================

print("\n每个Token的向量形状：")

for index, token in enumerate(tokens):
    token_vector = last_hidden_states[0, index]

    print(
        f"{index:<3}"
        f"{token:<12}"
        f"{token_vector.shape}"
    )


# ============================================================
# 14. 查看[CLS]向量
# ============================================================

cls_vector = last_hidden_states[0, 0]

print("\n[CLS]向量形状：")
print(cls_vector.shape)

print("\n[CLS]向量前10维：")
print(cls_vector[:10])

C:\Users\Administrator\.conda\envs\rl\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


本地模型文件检查成功！
config.json              0.00 MB
tokenizer_config.json    0.00 MB
tokenizer.json           0.44 MB
vocab.txt                0.22 MB
model.safetensors        420.05 MB

英文BERT分词器加载成功！
英文BERT模型加载成功！

原始文本：
Helloj, my dog is cute

分词结果：
['[CLS]', 'hello', '##j', ',', 'my', 'dog', 'is', 'cute', '[SEP]']

input_ids：
tensor([[  101,  7592,  3501,  1010,  2026,  3899,  2003, 10140,   102]])

attention_mask：
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])

token_type_ids：
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]])

输入Token数量：
9

最后一层隐藏状态形状：
torch.Size([1, 9, 768])

每个Token的向量形状：
0  [CLS]       torch.Size([768])
1  hello       torch.Size([768])
2  ##j         torch.Size([768])
3  ,           torch.Size([768])
4  my          torch.Size([768])
5  dog         torch.Size([768])
6  is          torch.Size([768])
7  cute        torch.Size([768])
8  [SEP]       torch.Size([768])

[CLS]向量形状：
torch.Size([768])

[CLS]向量前10维：
tensor([ 0.0084,  0.2637,  0.0667, -0.2227, -0.2781, -0.3346, -0.0264,  0.3443,
    

第 8 段：Doc2Vec（Gensim）

In [1]:
from gensim.models import Doc2Vec
from gensim.models.doc2vec import TaggedDocument

# 准备语料（分词后的文档列表）
corpus = [
    ['this', 'is', 'the', 'first', 'document'],
    ['this', 'document', 'is', 'the', 'second', 'document'],
    ['and', 'this', 'is', 'the', 'third', 'one'],
    ['is', 'this', 'the', 'first', 'document']
]

# 为每个文档打标签
documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(corpus)]

# 训练 Doc2Vec 模型
model = Doc2Vec(documents, vector_size=100, window=5, min_count=1, workers=4)

# 推断新文档的向量
new_vector = model.infer_vector(["new", "document", "text"])
print("新文档的向量（前10维）:", new_vector[:10])

# 获取已训练文档的向量
doc_vector = model.dv[0]
print("文档0的向量（前10维）:", doc_vector[:10])

新文档的向量（前10维）: [-4.4092694e-03 -2.8076568e-03 -2.2324563e-03  6.4043066e-05
  3.9779991e-03 -4.6696814e-04 -8.8533910e-04 -3.4403054e-03
 -1.9816413e-04  3.6636898e-03]
文档0的向量（前10维）: [-0.00523184 -0.00597958 -0.00988014  0.00855307  0.00356682  0.00026251
 -0.00987986 -0.00516668 -0.00971758  0.002011  ]


第 9 段：Sentence-BERT 句向量

In [5]:
from sentence_transformers import SentenceTransformer

# 加载预训练模型
model = SentenceTransformer('all-MiniLM-L6-v2')

# 待编码的句子
sentences = [
    "This is an example sentence",
    "Each sentence is converted"
]

# 生成句向量
embeddings = model.encode(sentences)

print("句子数量:", len(embeddings))
print("每个句向量的维度:", embeddings[0].shape)
print("句向量:\n", embeddings)

C:\Users\Administrator\.conda\envs\rl\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


句子数量: 2
每个句向量的维度: (384,)
句向量:
 [[ 6.76569417e-02  6.34959564e-02  4.87131029e-02  7.93048963e-02
   3.74480709e-02  2.65277619e-03  3.93749177e-02 -7.09846616e-03
   5.93614057e-02  3.15370224e-02  6.00980818e-02 -5.29052354e-02
   4.06067409e-02 -2.59308442e-02  2.98428535e-02  1.12691487e-03
   7.35148937e-02 -5.03818579e-02 -1.22386597e-01  2.37028375e-02
   2.97265276e-02  4.24768776e-02  2.56337691e-02  1.99514348e-03
  -5.69190495e-02 -2.71597989e-02 -3.29035297e-02  6.60248995e-02
   1.19007193e-01 -4.58791330e-02 -7.26214200e-02 -3.25840116e-02
   5.23414016e-02  4.50553410e-02  8.25305004e-03  3.67024243e-02
  -1.39415674e-02  6.53918684e-02 -2.64272075e-02  2.06393175e-04
  -1.36643527e-02 -3.62811014e-02 -1.95043907e-02 -2.89738420e-02
   3.94270532e-02 -8.84090662e-02  2.62423488e-03  1.36713171e-02
   4.83062454e-02 -3.11566181e-02 -1.17329188e-01 -5.11690676e-02
  -8.85287672e-02 -2.18963325e-02  1.42986281e-02  4.44167778e-02
  -1.34816021e-02  7.43392631e-02  2.66382936

第 10 段：LDA 主题模型

In [3]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

# 构建词频矩阵
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

# 训练 LDA 模型（假设2个主题）
lda = LatentDirichletAllocation(n_components=2, random_state=42)
lda.fit(X)

# 打印每个主题的关键词
feature_names = vectorizer.get_feature_names_out()
for topic_idx, topic in enumerate(lda.components_):
    top_words_idx = topic.argsort()[-5:][::-1]  # 取权重最高的5个词
    top_words = [feature_names[i] for i in top_words_idx]
    print(f"主题 {topic_idx}: {top_words}")

# 查看每个文档的主题分布
doc_topic_dist = lda.transform(X)
print("\n文档-主题分布:\n", doc_topic_dist)

主题 0: ['this', 'the', 'is', 'and', 'third']
主题 1: ['document', 'is', 'the', 'this', 'first']

文档-主题分布:
 [[0.09925844 0.90074156]
 [0.08332892 0.91667108]
 [0.89341739 0.10658261]
 [0.09925844 0.90074156]]


补充：完整的文本表示对比示例

In [4]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec, Doc2Vec
from gensim.models.doc2vec import TaggedDocument

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

# 1. 词袋模型
bow_vectorizer = CountVectorizer()
bow_matrix = bow_vectorizer.fit_transform(corpus)
print("词袋模型矩阵形状:", bow_matrix.shape)

# 2. TF-IDF
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)
print("TF-IDF矩阵形状:", tfidf_matrix.shape)

# 3. Word2Vec（需先分词）
tokenized_corpus = [doc.lower().split() for doc in corpus]
w2v_model = Word2Vec(tokenized_corpus, vector_size=50, min_count=1)
# 文档向量 = 词向量平均
doc_vectors = []
for tokens in tokenized_corpus:
    vecs = [w2v_model.wv[word] for word in tokens if word in w2v_model.wv]
    if vecs:
        doc_vectors.append(np.mean(vecs, axis=0))
    else:
        doc_vectors.append(np.zeros(50))
print("Word2Vec文档向量形状:", np.array(doc_vectors).shape)

词袋模型矩阵形状: (4, 9)
TF-IDF矩阵形状: (4, 9)
Word2Vec文档向量形状: (4, 50)
