词袋模型（Bag of Words）

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ["我喜欢自然语言处理", "我爱学习NLP技术", "文本相似度计算很有趣"]

vectorizer = CountVectorizer(analyzer="char", ngram_range=(1, 2), lowercase=False)
bow_matrix = vectorizer.fit_transform(corpus)

print("词频矩阵:", bow_matrix.toarray())
print("特征名称:", vectorizer.get_feature_names_out())

词频矩阵: [[0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1
  0 0 1 0 0 0 0 1 1 1 1 0 0 1 1 0]
 [1 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0
  1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0
  0 0 0 1 1 1 1 0 0 0 0 1 1 0 0 1]]
特征名称: ['L' 'LP' 'N' 'NL' 'P' 'P技' '习' '习N' '似' '似度' '喜' '喜欢' '处' '处理' '学' '学习'
 '度' '度计' '很' '很有' '我' '我喜' '我爱' '技' '技术' '文' '文本' '有' '有趣' '本' '本相' '术'
 '欢' '欢自' '然' '然语' '爱' '爱学' '理' '相' '相似' '算' '算很' '自' '自然' '言' '言处' '计'
 '计算' '语' '语言' '趣']


TF-IDF 方法

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = ["我喜欢自然语言处理", "我爱学习NLP技术", "文本相似度计算很有趣"]

corpus_tfidf = TfidfVectorizer(analyzer="char", ngram_range=(1, 2), lowercase=False)
corpus_tfidf_matrix = corpus_tfidf.fit_transform(corpus)

print("TF-IDF矩阵:", corpus_tfidf_matrix.toarray())
print("特征名称:", corpus_tfidf.get_feature_names_out())

TF-IDF矩阵: [[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.24560019 0.24560019
  0.24560019 0.24560019 0.         0.         0.         0.
  0.         0.         0.18678528 0.24560019 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.24560019 0.24560019 0.24560019 0.24560019
  0.         0.         0.24560019 0.         0.         0.
  0.         0.24560019 0.24560019 0.24560019 0.24560019 0.
  0.         0.24560019 0.24560019 0.        ]
 [0.24560019 0.24560019 0.24560019 0.24560019 0.24560019 0.24560019
  0.24560019 0.24560019 0.         0.         0.         0.
  0.         0.         0.24560019 0.24560019 0.         0.
  0.         0.         0.18678528 0.         0.24560019 0.24560019
  0.24560019 0.         0.         0.         0.         0.
  0.         0.24560019 0.         0.         0.         0.
  0.24560019 0.24560019 0.         0.         0.         0.
  0.       

Word2Vec 词向量

In [4]:
from gensim.models import Word2Vec

sentences = [
    ['我', '喜欢', '自然语言处理'],
    ['我', '爱', '学习', 'NLP', '技术'],
    ['文本', '相似度', '计算', '很', '有趣']
]

model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)

# 获取词向量
vector = model.wv['自然语言处理']
print("'自然语言处理' 的词向量（前10维）:", vector[:10])

'自然语言处理' 的词向量（前10维）: [ 0.0070888  -0.00156793  0.0079475  -0.00948866 -0.0080295  -0.00664037
 -0.00400345  0.00498922 -0.00381356 -0.00831991]


句子向量计算

In [5]:
import numpy as np

def sentence_vector(sentence, model):
    vectors = [model.wv[word] for word in sentence if word in model.wv]
    return np.mean(vectors, axis=0) if vectors else np.zeros(model.vector_size)

# 计算两个句子的向量
sentence_vec1 = sentence_vector(['我', '喜欢', '自然语言处理'], model)
sentence_vec2 = sentence_vector(['我', '爱', 'NLP'], model)

print("句子1向量（前10维）:", sentence_vec1[:10])
print("句子2向量（前10维）:", sentence_vec2[:10])

句子1向量（前10维）: [ 0.00544095  0.00227787  0.00477727  0.0015394  -0.00530811 -0.00673745
  0.00034246  0.00680379 -0.0044821  -0.00535878]
句子2向量（前10维）: [ 0.00082522 -0.00362498  0.00210398  0.00852455 -0.00524017 -0.00455622
  0.00219299  0.00339693 -0.00448151 -0.00467512]


BERT 相似度计算

In [5]:
from pathlib import Path

import torch
from transformers import AutoModel, AutoTokenizer
# ============================================================
# 1. 指定本地中文BERT模型目录
#
# 注意：
# 从你的截图看，文件夹名称是 bertbert-base-chinese
# ============================================================
model_dir = Path(r"D:\11\NLP\data\bertbert-base-chinese")
# ============================================================
# 2. 检查模型文件夹
# ============================================================
if not model_dir.is_dir():
    raise FileNotFoundError(f"模型文件夹不存在：{model_dir}\n""请检查左侧项目目录中的真实文件夹名称。")

print("本地模型目录：")
print(model_dir)
print("\n文件夹中的文件：")
for file_path in model_dir.iterdir():
    print(file_path.name)
# ============================================================
# 3. 检查必要文件
# ============================================================
required_basic_files = [ "config.json","vocab.txt"]
missing_files = []
for file_name in required_basic_files:
    if not (model_dir / file_name).is_file():
        missing_files.append(file_name)

# 模型权重可能是两种格式之一
has_model_weights = ((model_dir / "model.safetensors").is_file() or(model_dir / "pytorch_model.bin").is_file())

if missing_files:
    raise FileNotFoundError("中文BERT文件不完整，缺少：\n" + "\n".join(missing_files))

if not has_model_weights:
    raise FileNotFoundError(
        "模型文件夹中没有找到模型权重。\n"
        "至少需要下面其中一个文件：\n"
        "model.safetensors\n"
        "pytorch_model.bin\n\n"
        f"当前目录：{model_dir}"
    )

print("\n模型基础文件检查成功！")

# ============================================================
# 4. 完全从本地加载分词器
# ============================================================
tokenizer = AutoTokenizer.from_pretrained(str(model_dir), local_files_only=True,use_fast=True)
# ============================================================
# 5. 完全从本地加载BERT模型
# ============================================================
model = AutoModel.from_pretrained(str(model_dir),local_files_only=True)
# 切换为推理模式
model.eval()
print("中文BERT分词器加载成功！")
print("中文BERT模型加载成功！")

# ============================================================
# 6. 输入中文文本
# ============================================================
text = "这是一个示例句子。"

# ============================================================
# 7. 文本编码
# ============================================================
inputs = tokenizer(text,return_tensors="pt")

# ============================================================
# 8. 查看分词结果
# ============================================================
tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])

print("\n原始文本：")
print(text)
print("\n分词结果：")
print(tokens)
print("\ninput_ids：")
print(inputs["input_ids"])
print("\nattention_mask：")
print(inputs["attention_mask"])

# ============================================================
# 9. BERT前向传播
# ============================================================
with torch.no_grad():
    outputs = model(**inputs)

# ============================================================
# 10. 获取最后一层隐藏状态
#
# 注意：正确名称是 last_hidden_state
# 不是 last_hidden_states
# ============================================================
last_hidden_states = outputs.last_hidden_state

# ============================================================
# 11. 输出结果
# ============================================================
print("\n输入Token数量：")
print(inputs["input_ids"].shape[1])
print("\n最后一层隐藏状态形状：")
print(last_hidden_states.shape)

# ============================================================
# 12. 查看每个Token对应的向量
# ============================================================

print("\n每个Token对应的向量形状：")
for index, token in enumerate(tokens):
    token_vector = last_hidden_states[0, index]
    print(
        f"{index:<3}"
        f"{token:<12}"
        f"{token_vector.shape}"
    )

# ============================================================
# 13. 查看[CLS]向量
# ============================================================
cls_vector = last_hidden_states[0, 0]
print("\n[CLS]向量形状：")
print(cls_vector.shape)
print("\n[CLS]向量前10维：")
print(cls_vector[:10])

C:\Users\Administrator\.conda\envs\rl\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


本地模型目录：
D:\11\NLP\data\bertbert-base-chinese

文件夹中的文件：
config.json
model.safetensors
tokenizer_config.json
vocab.txt

模型基础文件检查成功！
中文BERT分词器加载成功！
中文BERT模型加载成功！

原始文本：
这是一个示例句子。

分词结果：
['[CLS]', '这', '是', '一', '个', '示', '例', '句', '子', '。', '[SEP]']

input_ids：
tensor([[ 101, 6821, 3221,  671,  702, 4850,  891, 1368, 2094,  511,  102]])

attention_mask：
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

输入Token数量：
11

最后一层隐藏状态形状：
torch.Size([1, 11, 768])

每个Token对应的向量形状：
0  [CLS]       torch.Size([768])
1  这           torch.Size([768])
2  是           torch.Size([768])
3  一           torch.Size([768])
4  个           torch.Size([768])
5  示           torch.Size([768])
6  例           torch.Size([768])
7  句           torch.Size([768])
8  子           torch.Size([768])
9  。           torch.Size([768])
10 [SEP]       torch.Size([768])

[CLS]向量形状：
torch.Size([768])

[CLS]向量前10维：
tensor([-0.4721,  0.4729,  0.9732,  0.0935,  0.4640, -1.0551, -0.3472, -0.8601,
        -0.3091,  1.2714])


余弦相似度计算

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_12 = cosine_similarity(corpus_tfidf_matrix[0:1], corpus_tfidf_matrix[1:2])[0][0]
similarity_13 = cosine_similarity(corpus_tfidf_matrix[0:1], corpus_tfidf_matrix[2:3])[0][0]

print(f"文本1与文本2的相似度: {similarity_12:.4f}")
print(f"文本1与文本3的相似度: {similarity_13:.4f}")

文本1与文本2的相似度: 0.0349
文本1与文本3的相似度: 0.0000


新闻标题相似度检测

In [14]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

titles = ["苹果发布新款iPhone手机", "苹果公司推出最新智能手机", "微软公布季度财报", "谷歌宣布新的人工智能计划"]

title_tfidf = TfidfVectorizer(analyzer="char", ngram_range=(1, 2), lowercase=False)
title_tfidf_matrix = title_tfidf.fit_transform(titles)
title_similarities = cosine_similarity(title_tfidf_matrix)

df = pd.DataFrame(title_similarities, columns=titles, index=titles)
print(df.round(4))

                苹果发布新款iPhone手机  苹果公司推出最新智能手机  微软公布季度财报  谷歌宣布新的人工智能计划
苹果发布新款iPhone手机          1.0000        0.1992    0.0226        0.0662
苹果公司推出最新智能手机            0.1992        1.0000    0.0385        0.1169
微软公布季度财报                0.0226        0.0385    1.0000        0.0241
谷歌宣布新的人工智能计划            0.0662        0.1169    0.0241        1.0000


补充 1：Jaccard 相似度

In [8]:
def jaccard_similarity(text1, text2):
    # 分词（简单按字分割）
    set1 = set(text1)
    set2 = set(text2)
    intersection = len(set1 & set2)
    union = len(set1 | set2)
    return intersection / union if union > 0 else 0

# 测试
text1 = "我喜欢自然语言处理"
text2 = "我爱学习NLP技术"
print(f"Jaccard相似度: {jaccard_similarity(text1, text2):.4f}")

Jaccard相似度: 0.0588


补充 2：欧氏距离与曼哈顿距离

In [16]:
from scipy.spatial.distance import euclidean, cityblock

vec1 = corpus_tfidf_matrix[0].toarray().flatten()
vec2 = corpus_tfidf_matrix[1].toarray().flatten()

euclidean_dist = euclidean(vec1, vec2)
manhattan_dist = cityblock(vec1, vec2)

print(f"欧氏距离: {euclidean_dist:.4f}")
print(f"曼哈顿距离: {manhattan_dist:.4f}")

欧氏距离: 1.3893
曼哈顿距离: 7.8592


补充 3：使用 Sentence-BERT 计算语义相似度

In [9]:
from sentence_transformers import SentenceTransformer, models, util

# 你的本地模型路径
local_model_path = r"D:\11\NLP\data\paraphrase-multilingual-MiniLM-L12-v2"

# 方法：手动组合模型模块（避开自动解析的 Bug）
# 1. 加载 Transformer 底座（它会自动去读你文件夹里的 config.json 和 model.safetensors）
word_embedding_model = models.Transformer(local_model_path)

# 2. 从这里直接获取正确的维度（这就解决了找不到 word_embedding_dimension 的问题）
dim = word_embedding_model.get_word_embedding_dimension()

# 3. 添加池化层（把词向量变成句子向量）
pooling_model = models.Pooling(dim)

# 4. 组合为最终的 SentenceTransformer
model = SentenceTransformer(modules=[word_embedding_model, pooling_model])

# -------------------------------------------------------------
# 下面是你原本的代码，保持不变即可：

# 待比较的句子
sentences = [
    "苹果发布新款iPhone手机",
    "苹果公司推出最新智能手机",
    "微软公布季度财报"
]

# 生成句子向量
embeddings = model.encode(sentences)

# 计算相似度
cos_sim = util.cos_sim(embeddings, embeddings)

print("相似度矩阵:\n", cos_sim)

C:\Users\Administrator\.conda\envs\rl\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


相似度矩阵:
 tensor([[1.0000, 0.9054, 0.0927],
        [0.9054, 1.0000, 0.2248],
        [0.0927, 0.2248, 1.0000]])


补充 4：完整的文本相似度对比函数

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def compare_texts(text1, text2):
    results = {}

    tfidf_vectorizer = TfidfVectorizer(analyzer="char", ngram_range=(1, 2), lowercase=False)
    tfidf_vectors = tfidf_vectorizer.fit_transform([text1, text2])
    results["TF-IDF余弦相似度"] = cosine_similarity(tfidf_vectors[0:1], tfidf_vectors[1:2])[0][0]

    set1, set2 = set(text1), set(text2)
    results["Jaccard相似度"] = len(set1 & set2) / len(set1 | set2) if len(set1 | set2) > 0 else 0

    count_vectorizer = CountVectorizer(analyzer="char", ngram_range=(1, 2), lowercase=False)
    count_vectors = count_vectorizer.fit_transform([text1, text2])
    results["词袋余弦相似度"] = cosine_similarity(count_vectors[0:1], count_vectors[1:2])[0][0]

    return results

text_a = "苹果发布新款iPhone手机"
text_b = "苹果公司推出最新智能手机"
results = compare_texts(text_a, text_b)

for method, score in results.items():
    print(f"{method}: {score:.4f}")

TF-IDF余弦相似度: 0.1652
Jaccard相似度: 0.2381
词袋余弦相似度: 0.2809
